# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-07 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dest_price',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='src2btc',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='src_btc_price',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=32),
            preserve_default=False,
        ),
    ]
