# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-15 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_walletaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletaddress',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
