# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-18 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tube',
            fields=[
                ('tube_id', models.AutoField(primary_key=True, serialize=False)),
                ('ex1_name', models.CharField(max_length=10)),
                ('ex2_name', models.CharField(max_length=10)),
                ('ex3_name', models.CharField(max_length=10)),
                ('set_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('ex1_bid_start_time', models.DateTimeField(blank=True, null=True)),
                ('ex1_bid_end_time', models.DateTimeField(blank=True, null=True)),
                ('ex1_with_start_time', models.DateTimeField(blank=True, null=True)),
                ('ex1_with_end_time', models.DateTimeField(blank=True, null=True)),
                ('ex2_depo_start_time', models.DateTimeField(blank=True, null=True)),
                ('ex2_ask_start_time', models.DateTimeField(blank=True, null=True)),
                ('ex2_ask_end_time', models.DateTimeField(blank=True, null=True)),
                ('ex2_bid_start_time', models.DateTimeField(blank=True, null=True)),
                ('ex2_bid_end_time', models.DateTimeField(blank=True, null=True)),
                ('ex2_with_start_time', models.DateTimeField(blank=True, null=True)),
                ('ex2_with_end_time', models.DateTimeField(blank=True, null=True)),
                ('ex3_depo_start_time', models.DateTimeField(blank=True, null=True)),
                ('ex3_ask_start_time', models.DateTimeField(blank=True, null=True)),
                ('ex3_ask_end_time', models.DateTimeField(blank=True, null=True)),
                ('ex1_bid_alt_price', models.DecimalField(decimal_places=8, max_digits=32)),
                ('ex1_bid_bit_price', models.DecimalField(decimal_places=8, max_digits=32)),
                ('ex1_bid_alt_value', models.DecimalField(decimal_places=8, max_digits=32)),
                ('ex2_dest_alt_value', models.DecimalField(decimal_places=8, max_digits=32)),
                ('ex1_src_bit_price', models.DecimalField(decimal_places=8, max_digits=32)),
                ('ex1_src_alt_price', models.DecimalField(decimal_places=8, max_digits=32)),
                ('ex1_src_alt_value', models.DecimalField(decimal_places=8, max_digits=32)),
                ('ex2_ask_alt_value', models.DecimalField(decimal_places=8, max_digits=32)),
                ('ex3_dest_bit_price', models.DecimalField(decimal_places=8, max_digits=32)),
                ('ex3_dest_alt_price', models.DecimalField(decimal_places=8, max_digits=32)),
                ('ex3_dest_alt_value', models.DecimalField(decimal_places=8, max_digits=32)),
                ('ex2_bid_alt_value', models.DecimalField(decimal_places=8, max_digits=32)),
                ('ex3_ask_bit_price', models.DecimalField(decimal_places=8, max_digits=32)),
                ('ex3_ask_alt_price', models.DecimalField(decimal_places=8, max_digits=32)),
                ('ex3_ask_alt_value', models.DecimalField(decimal_places=8, max_digits=32)),
                ('ex2_src_alt_value', models.DecimalField(decimal_places=8, max_digits=32)),
                ('ex1_bid_order_id', models.CharField(max_length=255)),
                ('ex1_coin_code', models.CharField(max_length=10)),
                ('ex1_coin_amt', models.DecimalField(decimal_places=8, max_digits=32)),
                ('ex2_ask_order_id', models.CharField(max_length=255)),
                ('ex2_ask_coin_code', models.CharField(max_length=10)),
                ('ex2_ask_coin_amt', models.DecimalField(decimal_places=8, max_digits=32)),
                ('ex2_bid_order_id', models.CharField(max_length=255)),
                ('ex2_bid_coin_code', models.CharField(max_length=10)),
                ('ex2_bid_coin_amt', models.DecimalField(decimal_places=8, max_digits=32)),
                ('ex3_bid_order_id', models.CharField(max_length=255)),
                ('ex3_coin_code', models.CharField(max_length=10)),
                ('ex3_coin_amt', models.DecimalField(decimal_places=8, max_digits=32)),
            ],
        ),
    ]
