# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-28 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0007_withdrawalfee'),
        ('tube', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tube_id', models.BigIntegerField()),
                ('step', models.IntegerField()),
                ('event', models.IntegerField(choices=[(0, 'INIT'), (1, 'CLOSE'), (2, 'BID'), (3, 'ASK'), (4, 'WITHDRAWAL'), (5, 'DEPOSIT'), (6, 'ERROR')])),
                ('price', models.BigIntegerField()),
                ('time_stamp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=255)),
                ('order_type', models.CharField(max_length=10)),
                ('coin_amt', models.DecimalField(decimal_places=8, max_digits=32)),
                ('value', models.DecimalField(decimal_places=8, max_digits=32)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.Exchange')),
                ('market_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_base_currency', to='exchange.Currency')),
                ('market_counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_counter_currency', to='exchange.Currency')),
            ],
        ),
        migrations.CreateModel(
            name='TransferInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coin_amt', models.DecimalField(decimal_places=8, max_digits=32)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.Currency')),
                ('dest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_exchange', to='exchange.Exchange')),
                ('src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_exchange', to='exchange.Exchange')),
            ],
        ),
        migrations.DeleteModel(
            name='Tube',
        ),
    ]
