# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-28 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0003_auto_20180428_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='eventinfo_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
