# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-28 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0005_auto_20180428_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferinfo',
            name='transfer_type',
            field=models.IntegerField(choices=[(0, 'DEPOSIT'), (1, 'WITHDRAWAL')], default=0),
            preserve_default=False,
        ),
    ]
