# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-05 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0006_transferinfo_transfer_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventlog',
            old_name='step',
            new_name='stage',
        ),
    ]
